/**
 * @license
 * SPDX-License-Identifier: Apache-2.0
 */

import {
  Employee,
  JobOpening,
  Candidate,
  DocumentFile,
  AttendanceRecord,
  PayrollRecord,
  LoanRequest,
  FeedbackItem,
  ExitCase,
  SettingsConfig,
} from './types';

export const initialEmployees: Employee[] = [
  {
    id: 'EMP001',
    name: 'Sarah Connor',
    email: 's.connor@alokcorp.com',
    phone: '+91 9876543210',
    department: 'Corporate HR',
    role: 'Chief Human Resources Officer',
    status: 'Active',
    joinDate: '2021-03-15',
    salary: 180000,

    // Employee Master Fields
    Employee_Code: 'EMP001',
    Salutation: 'Mrs.',
    Employee_Name: 'Sarah Connor',
    Employee_Status: 'Active',
    Employment_Type: 'Full-time',
    Gender: 'Female',
    Present_Address1: 'Flat 502, Wing-A, Lodha Excelus',
    Present_Address2: 'Apollo Mills Compound, Mahalaxmi',
    Present_City: 'Mumbai',
    Present_State: 'Maharashtra',
    Present_Pin: '400011',
    Permanent_Address1: 'Flat 502, Wing-A, Lodha Excelus',
    Permanent_Address2: 'Apollo Mills Compound, Mahalaxmi',
    PermanentCity: 'Mumbai',
    PermanentState: 'Maharashtra',
    Permanent_Pin: '400011',
    Marital_Status: 'Married',
    Father_Name: 'John Connor Sr.',
    Date_of_Birth: '1985-05-24',
    Blood_Group: 'O+0',
    Date_Of_Joining: '2021-03-15',
    Date_Of_Leaving: '',
    Reason_Leaving: '',
    Date_of_confirmation: '2021-09-15',
    Emergency_Contact_Person: 'John Connor',
    Emergency_Contact_Number: '+91 9876543211',
    Spouse_Name: 'John Connor',
    Spouse_DOB: '1983-11-12',
    Child_Name_1: 'Thomas Connor',
    Child_1_DOB: '2012-08-04',
    Child_Name_2: 'Lily Connor',
    Child_2_DOB: '2015-02-14',
    PAN: 'ABCDE1234F',
    ESIC_Account_Number: '3112345678901234',
    IFSCCode: 'HDFC0000060',
    Bank_Name: 'HDFC Bank',
    Bank_Branch_Name: 'Mahalaxmi Branch',
    Bank_Acct_No: '50100234567890',
    Payment_Description: 'Bank Transfer',
    Pf_Base_Salary: 15000,
    EPS_Base_Salary_Limit: 15000,
    Official_Email: 's.connor@alokcorp.com',
    Personal_Email: 'sarah.connor.personal@gmail.com',
    UAN_No: '100123456789',
    ReportingManager_Name: 'Alok Jiwrajka',
    ReportingManager_Code: 'MGR001',
    Company_Description: 'ALOK Corporate',
    Department_Description: 'Corporate HR',
    Designation_Description: 'Chief Human Resources Officer',
    FirstName: 'Sarah',
    Grade_Code: 'E10',
    Grade_Description: 'Executive Leadership',
    Location2_Description: 'HQ - Mumbai Office',

    // Monthly Salary Breakdown
    Basic_Salary: 90000,
    Medical: 1250,
    Special_Allowance: 35000,
    Stipend: 0,
    Food_Coupon_Allowance: 3000,
    House_Rent_Allowance: 36000,
    Conveyance_Allowance: 1600,
    Education_Allowance: 200,
    DA: 0,
    Displacement_Allow: 0,
    Statutory_Bonus: 7000,
    Leave_Travel_Allowance_CTC: 5000,
    LWF: 150,
    Transport_Allowance: 2000,
    Employer_PF: 1800,
    Employer_ESIC: 0,
    Employee_ESIC: 0,
    Variable_Incentive_CTC: 15000,
    Gratuity: 4330,
    MONTHLY_GROSS: 180000,
    MonthlyCTC: 201130,

    // Annual
    ANNUAL_GROSS: 2160000,
    TOTALCTC: 2413560,
  },
  {
    id: 'EMP002',
    name: 'James Carter',
    email: 'j.carter@alokind.com',
    phone: '+91 9876543220',
    department: 'Spinning Operations',
    role: 'Senior Plant Manager',
    status: 'Active',
    joinDate: '2022-01-10',
    salary: 120000,

    // Employee Master Fields
    Employee_Code: 'EMP002',
    Salutation: 'Mr.',
    Employee_Name: 'James Carter',
    Employee_Status: 'Active',
    Employment_Type: 'Full-time',
    Gender: 'Male',
    Present_Address1: 'Staff Quarters, Alok Industries Complex',
    Present_Address2: 'Silli-Masat Road, Silvassa',
    Present_City: 'Silvassa',
    Present_State: 'Dadra and Nagar Haveli',
    Present_Pin: '396230',
    Permanent_Address1: '12, Greenfield Apartments',
    Permanent_Address2: 'S.G. Highway, Bodakdev',
    PermanentCity: 'Ahmedabad',
    PermanentState: 'Gujarat',
    Permanent_Pin: '380054',
    Marital_Status: 'Married',
    Father_Name: 'Robert Carter',
    Date_of_Birth: '1988-10-12',
    Blood_Group: 'A+',
    Date_Of_Joining: '2022-01-10',
    Date_Of_Leaving: '',
    Reason_Leaving: '',
    Date_of_confirmation: '2022-07-10',
    Emergency_Contact_Person: 'Emily Carter',
    Emergency_Contact_Number: '+91 9876543221',
    Spouse_Name: 'Emily Carter',
    Spouse_DOB: '1990-04-18',
    Child_Name_1: 'Mason Carter',
    Child_1_DOB: '2018-12-05',
    Child_Name_2: '',
    Child_2_DOB: '',
    PAN: 'BCDEF2345G',
    ESIC_Account_Number: '3112345678901235',
    IFSCCode: 'ICIC0000102',
    Bank_Name: 'ICICI Bank',
    Bank_Branch_Name: 'Silvassa Branch',
    Bank_Acct_No: '002345678901',
    Payment_Description: 'Bank Transfer',
    Pf_Base_Salary: 15000,
    EPS_Base_Salary_Limit: 15000,
    Official_Email: 'j.carter@alokind.com',
    Personal_Email: 'j.carter.personal@outlook.com',
    UAN_No: '100123456790',
    ReportingManager_Name: 'Devendra Shinde',
    ReportingManager_Code: 'MGR004',
    Company_Description: 'ALOK Industries',
    Department_Description: 'Spinning Operations',
    Designation_Description: 'Senior Plant Manager',
    FirstName: 'James',
    Grade_Code: 'M5',
    Grade_Description: 'Management Grade 5',
    Location2_Description: 'Silvassa Plant',

    // Monthly Salary Breakdown
    Basic_Salary: 60000,
    Medical: 1250,
    Special_Allowance: 22000,
    Stipend: 0,
    Food_Coupon_Allowance: 2000,
    House_Rent_Allowance: 24000,
    Conveyance_Allowance: 1600,
    Education_Allowance: 0,
    DA: 0,
    Displacement_Allow: 5000,
    Statutory_Bonus: 4150,
    Leave_Travel_Allowance_CTC: 4000,
    LWF: 150,
    Transport_Allowance: 0,
    Employer_PF: 1800,
    Employer_ESIC: 0,
    Employee_ESIC: 0,
    Variable_Incentive_CTC: 10000,
    Gratuity: 2885,
    MONTHLY_GROSS: 120000,
    MonthlyCTC: 134685,

    // Annual
    ANNUAL_GROSS: 1440000,
    TOTALCTC: 1616220,
  },
  {
    id: 'EMP003',
    name: 'Elena Rostova',
    email: 'e.rostova@alokind.com',
    phone: '+91 9876543230',
    department: 'Weaving Unit',
    role: 'Quality Assurance Head',
    status: 'Active',
    joinDate: '2023-06-01',
    salary: 95000,

    // Employee Master Fields
    Employee_Code: 'EMP003',
    Salutation: 'Ms.',
    Employee_Name: 'Elena Rostova',
    Employee_Status: 'Active',
    Employment_Type: 'Full-time',
    Gender: 'Female',
    Present_Address1: 'Room 402, Royal Residency',
    Present_Address2: 'Umergaon Road, Vapi',
    Present_City: 'Vapi',
    Present_State: 'Gujarat',
    Present_Pin: '396191',
    Permanent_Address1: 'Room 402, Royal Residency',
    Permanent_Address2: 'Umergaon Road, Vapi',
    PermanentCity: 'Vapi',
    PermanentState: 'Gujarat',
    Permanent_Pin: '396191',
    Marital_Status: 'Single',
    Father_Name: 'Dmitry Rostov',
    Date_of_Birth: '1992-02-14',
    Blood_Group: 'B-',
    Date_Of_Joining: '2023-06-01',
    Date_Of_Leaving: '',
    Reason_Leaving: '',
    Date_of_confirmation: '2023-12-01',
    Emergency_Contact_Person: 'Irina Rostova',
    Emergency_Contact_Number: '+91 9876543231',
    Spouse_Name: '',
    Spouse_DOB: '',
    Child_Name_1: '',
    Child_1_DOB: '',
    Child_Name_2: '',
    Child_2_DOB: '',
    PAN: 'CDEFG3456H',
    ESIC_Account_Number: '3112345678901236',
    IFSCCode: 'SBIN0001234',
    Bank_Name: 'State Bank of India',
    Bank_Branch_Name: 'Vapi Industrial Area',
    Bank_Acct_No: '30456789012',
    Payment_Description: 'Bank Transfer',
    Pf_Base_Salary: 15000,
    EPS_Base_Salary_Limit: 15000,
    Official_Email: 'e.rostova@alokind.com',
    Personal_Email: 'elena.rostova.qa@gmail.com',
    UAN_No: '100123456791',
    ReportingManager_Name: 'James Carter',
    ReportingManager_Code: 'EMP002',
    Company_Description: 'ALOK Industries',
    Department_Description: 'Weaving Unit',
    Designation_Description: 'Quality Assurance Head',
    FirstName: 'Elena',
    Grade_Code: 'M2',
    Grade_Description: 'Management Grade 2',
    Location2_Description: 'Vapi Plant',

    // Monthly Salary Breakdown
    Basic_Salary: 47500,
    Medical: 1250,
    Special_Allowance: 19050,
    Stipend: 0,
    Food_Coupon_Allowance: 1000,
    House_Rent_Allowance: 19000,
    Conveyance_Allowance: 1600,
    Education_Allowance: 0,
    DA: 0,
    Displacement_Allow: 3000,
    Statutory_Bonus: 2600,
    Leave_Travel_Allowance_CTC: 3000,
    LWF: 150,
    Transport_Allowance: 0,
    Employer_PF: 1800,
    Employer_ESIC: 0,
    Employee_ESIC: 0,
    Variable_Incentive_CTC: 5000,
    Gratuity: 2285,
    MONTHLY_GROSS: 95000,
    MonthlyCTC: 104085,

    // Annual
    ANNUAL_GROSS: 1140000,
    TOTALCTC: 1249020,
  },
  {
    id: 'EMP004',
    name: 'Marcus Vance',
    email: 'm.vance@aloktextiles.com',
    phone: '+91 9876543240',
    department: 'Sales & Apparel',
    role: 'Regional Sales Manager',
    status: 'On Probation',
    joinDate: '2024-03-01',
    salary: 85000,

    // Employee Master Fields
    Employee_Code: 'EMP004',
    Salutation: 'Mr.',
    Employee_Name: 'Marcus Vance',
    Employee_Status: 'On Probation',
    Employment_Type: 'On Probation',
    Gender: 'Male',
    Present_Address1: '702, Skyline Heights',
    Present_Address2: 'S.V. Road, Bandra West',
    Present_City: 'Mumbai',
    Present_State: 'Maharashtra',
    Present_Pin: '400050',
    Permanent_Address1: 'Flat 4A, Green Meadows',
    Permanent_Address2: 'Kalyan Nagar',
    PermanentCity: 'Bangalore',
    PermanentState: 'Karnataka',
    Permanent_Pin: '560043',
    Marital_Status: 'Single',
    Father_Name: 'Charles Vance',
    Date_of_Birth: '1995-11-15',
    Blood_Group: 'B+',
    Date_Of_Joining: '2024-03-01',
    Date_Of_Leaving: '',
    Reason_Leaving: '',
    Date_of_confirmation: '',
    Emergency_Contact_Person: 'Charles Vance',
    Emergency_Contact_Number: '+91 9876543241',
    Spouse_Name: '',
    Spouse_DOB: '',
    Child_Name_1: '',
    Child_1_DOB: '',
    Child_Name_2: '',
    Child_2_DOB: '',
    PAN: 'DEFGH4567I',
    ESIC_Account_Number: '3112345678901237',
    IFSCCode: 'KKBK0000657',
    Bank_Name: 'Kotak Mahindra Bank',
    Bank_Branch_Name: 'Bandra Branch',
    Bank_Acct_No: '1023456789',
    Payment_Description: 'Bank Transfer',
    Pf_Base_Salary: 15000,
    EPS_Base_Salary_Limit: 15000,
    Official_Email: 'm.vance@aloktextiles.com',
    Personal_Email: 'marcus.vance.sales@yahoo.com',
    UAN_No: '100123456792',
    ReportingManager_Name: 'Sarah Connor',
    ReportingManager_Code: 'EMP001',
    Company_Description: 'ALOK Textiles',
    Department_Description: 'Sales & Apparel',
    Designation_Description: 'Regional Sales Manager',
    FirstName: 'Marcus',
    Grade_Code: 'S3',
    Grade_Description: 'Sales Grade 3',
    Location2_Description: 'Bandra Sales Office',

    // Monthly Salary Breakdown
    Basic_Salary: 42500,
    Medical: 1250,
    Special_Allowance: 16650,
    Stipend: 0,
    Food_Coupon_Allowance: 1000,
    House_Rent_Allowance: 17000,
    Conveyance_Allowance: 1600,
    Education_Allowance: 0,
    DA: 0,
    Displacement_Allow: 0,
    Statutory_Bonus: 2000,
    Leave_Travel_Allowance_CTC: 3000,
    LWF: 150,
    Transport_Allowance: 1000,
    Employer_PF: 1800,
    Employer_ESIC: 0,
    Employee_ESIC: 0,
    Variable_Incentive_CTC: 12000,
    Gratuity: 2045,
    MONTHLY_GROSS: 85000,
    MonthlyCTC: 100845,

    // Annual
    ANNUAL_GROSS: 1020000,
    TOTALCTC: 1210140,
  },
  {
    id: 'EMP005',
    name: 'Aisha Rahman',
    email: 'a.rahman@alokcorp.com',
    phone: '+91 9876543250',
    department: 'Corporate Finance',
    role: 'Senior Finance Analyst',
    status: 'Active',
    joinDate: '2022-09-22',
    salary: 115000,

    // Employee Master Fields
    Employee_Code: 'EMP005',
    Salutation: 'Ms.',
    Employee_Name: 'Aisha Rahman',
    Employee_Status: 'Active',
    Employment_Type: 'Full-time',
    Gender: 'Female',
    Present_Address1: '704, Royal Palms Residency',
    Present_Address2: 'Saki Naka, Andheri East',
    Present_City: 'Mumbai',
    Present_State: 'Maharashtra',
    Present_Pin: '400072',
    Permanent_Address1: '704, Royal Palms Residency',
    Permanent_Address2: 'Saki Naka, Andheri East',
    PermanentCity: 'Mumbai',
    PermanentState: 'Maharashtra',
    Permanent_Pin: '400072',
    Marital_Status: 'Single',
    Father_Name: 'Habibur Rahman',
    Date_of_Birth: '1993-04-15',
    Blood_Group: 'AB+',
    Date_Of_Joining: '2022-09-22',
    Date_Of_Leaving: '',
    Reason_Leaving: '',
    Date_of_confirmation: '2023-03-22',
    Emergency_Contact_Person: 'Habibur Rahman',
    Emergency_Contact_Number: '+91 9876543251',
    Spouse_Name: '',
    Spouse_DOB: '',
    Child_Name_1: '',
    Child_1_DOB: '',
    Child_Name_2: '',
    Child_2_DOB: '',
    PAN: 'EFGHI5678J',
    ESIC_Account_Number: '3112345678901238',
    IFSCCode: 'AXIS0000005',
    Bank_Name: 'Axis Bank',
    Bank_Branch_Name: 'Andheri East Branch',
    Bank_Acct_No: '912010034567890',
    Payment_Description: 'Bank Transfer',
    Pf_Base_Salary: 15000,
    EPS_Base_Salary_Limit: 15000,
    Official_Email: 'a.rahman@alokcorp.com',
    Personal_Email: 'aisha.rahman.finance@gmail.com',
    UAN_No: '100123456793',
    ReportingManager_Name: 'Sarah Connor',
    ReportingManager_Code: 'EMP001',
    Company_Description: 'ALOK Corporate',
    Department_Description: 'Corporate Finance',
    Designation_Description: 'Senior Finance Analyst',
    FirstName: 'Aisha',
    Grade_Code: 'M3',
    Grade_Description: 'Management Grade 3',
    Location2_Description: 'HQ - Mumbai Office',

    // Monthly Salary Breakdown
    Basic_Salary: 57500,
    Medical: 1250,
    Special_Allowance: 21600,
    Stipend: 0,
    Food_Coupon_Allowance: 2000,
    House_Rent_Allowance: 23000,
    Conveyance_Allowance: 1600,
    Education_Allowance: 0,
    DA: 0,
    Displacement_Allow: 0,
    Statutory_Bonus: 4000,
    Leave_Travel_Allowance_CTC: 4000,
    LWF: 150,
    Transport_Allowance: 0,
    Employer_PF: 1800,
    Employer_ESIC: 0,
    Employee_ESIC: 0,
    Variable_Incentive_CTC: 10000,
    Gratuity: 2765,
    MONTHLY_GROSS: 115000,
    MonthlyCTC: 129565,

    // Annual
    ANNUAL_GROSS: 1380000,
    TOTALCTC: 1554780,
  }
];

export const initialJobs: JobOpening[] = [
  {
    id: 'JOB001',
    title: 'Senior Staff Security Engineer',
    department: 'Engineering',
    location: 'Remote (US/Canada)',
    type: 'Full-time',
    status: 'Open',
    applicantsCount: 14,
  },
  {
    id: 'JOB002',
    title: 'Senior UI/UX Designer',
    department: 'Product',
    location: 'Hybrid (San Francisco, CA)',
    type: 'Full-time',
    status: 'Open',
    applicantsCount: 32,
  },
  {
    id: 'JOB003',
    title: 'Content Marketing Specialist',
    department: 'Marketing',
    location: 'Remote',
    type: 'Contract',
    status: 'Open',
    applicantsCount: 19,
  },
  {
    id: 'JOB004',
    title: 'Director of Talent Development',
    department: 'HR Operations',
    location: 'On-site (New York, NY)',
    type: 'Full-time',
    status: 'Draft',
    applicantsCount: 0,
  },
];

export const initialCandidates: Candidate[] = [
  {
    id: 'CAN001',
    name: 'Devon Lane',
    email: 'devon.lane@gmail.com',
    appliedRole: 'Senior Staff Security Engineer',
    appliedDate: '2026-06-18',
    status: 'Interview Scheduled',
    score: 5,
    notes: 'Strong in cloud security architecture and Kubernetes hardening.',
    interviewDate: '2026-06-25T14:00',
    interviewFeedback: 'Excellent security depth. Knows standard IAM policies and VPC configs thoroughly.',
    interviewInterviewer: 'Sarah Jenkins',
    salaryOffered: 120000,
  },
  {
    id: 'CAN002',
    name: 'Bessie Cooper',
    email: 'bessie.co@yahoo.com',
    appliedRole: 'Senior UI/UX Designer',
    appliedDate: '2026-06-20',
    status: 'Shortlisted',
    score: 4,
    notes: 'Beautiful portfolio with dynamic prototyping and motion layout examples.',
  },
  {
    id: 'CAN003',
    name: 'Kristin Watson',
    email: 'kristin.w@outlook.com',
    appliedRole: 'Senior Staff Security Engineer',
    appliedDate: '2026-06-12',
    status: 'Selected',
    score: 5,
    notes: 'Outstanding technical assessment and systems design loop.',
    interviewDate: '2026-06-15T10:00',
    interviewFeedback: 'We must hire her as soon as possible. High emotional intelligence as well.',
    interviewInterviewer: 'Alexander Pierce',
    salaryOffered: 145000,
  },
  {
    id: 'CAN004',
    name: 'Jerome Bell',
    email: 'jbell.design@gmail.com',
    appliedRole: 'Senior UI/UX Designer',
    appliedDate: '2026-06-14',
    status: 'New',
    score: 3,
    notes: 'Clean visual layouts. Needs more experience with full design system guidelines.',
  },
  {
    id: 'CAN005',
    name: 'Arlene McCoy',
    email: 'arlene.mccoy@hotmail.com',
    appliedRole: 'Content Marketing Specialist',
    appliedDate: '2026-06-22',
    status: 'Rejected',
    score: 2,
    notes: 'Failed to complete pre-interview assignment.',
  },
];

export const initialDocuments: DocumentFile[] = [
  {
    id: 'DOC001',
    name: 'Employee_Handbook_2026_v2.pdf',
    category: 'Policies',
    size: '2.4 MB',
    uploadedAt: '2026-01-05',
    uploadedBy: 'Sarah Connor',
  },
  {
    id: 'DOC002',
    name: 'Standard_NDA_Template.docx',
    category: 'Templates',
    size: '142 KB',
    uploadedAt: '2025-11-12',
    uploadedBy: 'Thomas Wright',
  },
  {
    id: 'DOC003',
    name: 'Health_Insurance_Benefits_Guide_2026.pdf',
    category: 'Policies',
    size: '4.1 MB',
    uploadedAt: '2025-12-18',
    uploadedBy: 'Elena Rostova',
  },
  {
    id: 'DOC004',
    name: 'Contract_Aisha_Rahman_Executed.pdf',
    category: 'Contracts',
    size: '1.2 MB',
    uploadedAt: '2022-09-20',
    uploadedBy: 'Olivia Martinez',
  },
];

export const initialAttendance: AttendanceRecord[] = [
  {
    id: 'ATT001',
    employeeName: 'Sarah Connor',
    employeeRole: 'Lead Systems Architect',
    department: 'Engineering',
    date: '2026-06-24',
    checkIn: '08:52 AM',
    checkOut: null,
    status: 'On Time',
  },
  {
    id: 'ATT002',
    employeeName: 'James Carter',
    employeeRole: 'Senior Product Manager',
    department: 'Product',
    date: '2026-06-24',
    checkIn: '09:05 AM',
    checkOut: null,
    status: 'On Time',
  },
  {
    id: 'ATT003',
    employeeName: 'Elena Rostova',
    employeeRole: 'Growth Marketing Lead',
    department: 'Marketing',
    date: '2026-06-24',
    checkIn: '09:12 AM',
    checkOut: null,
    status: 'Late',
  },
  {
    id: 'ATT004',
    employeeName: 'Aisha Rahman',
    employeeRole: 'Senior Frontend Developer',
    department: 'Engineering',
    date: '2026-06-24',
    checkIn: '08:45 AM',
    checkOut: '05:30 PM',
    status: 'On Time',
  },
  {
    id: 'ATT005',
    employeeName: 'Thomas Wright',
    employeeRole: 'Talent Acquisition Partner',
    department: 'HR Operations',
    date: '2026-06-24',
    checkIn: '08:58 AM',
    checkOut: null,
    status: 'On Time',
  },
  {
    id: 'ATT006',
    employeeName: 'Olivia Martinez',
    employeeRole: 'Financial Controller',
    department: 'Finance',
    date: '2026-06-24',
    checkIn: '09:35 AM',
    checkOut: null,
    status: 'Late',
  },
];

export const initialPayroll: PayrollRecord[] = [
  {
    id: 'PAY001',
    employeeId: 'EMP001',
    employeeName: 'Sarah Connor',
    department: 'Engineering',
    baseSalary: 11250, // Monthly (135,000 / 12)
    allowances: 450,
    deductions: 380,
    netPay: 11320,
    paymentStatus: 'Paid',
    payPeriod: 'June 2026',
  },
  {
    id: 'PAY002',
    employeeId: 'EMP002',
    employeeName: 'James Carter',
    department: 'Product',
    baseSalary: 10000,
    allowances: 350,
    deductions: 320,
    netPay: 10030,
    paymentStatus: 'Paid',
    payPeriod: 'June 2026',
  },
  {
    id: 'PAY003',
    employeeId: 'EMP003',
    employeeName: 'Elena Rostova',
    department: 'Marketing',
    baseSalary: 7916.67,
    allowances: 250,
    deductions: 210,
    netPay: 7956.67,
    paymentStatus: 'Paid',
    payPeriod: 'June 2026',
  },
  {
    id: 'PAY004',
    employeeId: 'EMP005',
    employeeName: 'Aisha Rahman',
    department: 'Engineering',
    baseSalary: 9583.33,
    allowances: 300,
    deductions: 280,
    netPay: 9603.33,
    paymentStatus: 'Processing',
    payPeriod: 'June 2026',
  },
  {
    id: 'PAY005',
    employeeId: 'EMP006',
    employeeName: 'Thomas Wright',
    department: 'HR Operations',
    baseSalary: 6500,
    allowances: 150,
    deductions: 130,
    netPay: 6520,
    paymentStatus: 'Processing',
    payPeriod: 'June 2026',
  },
  {
    id: 'PAY006',
    employeeId: 'EMP007',
    employeeName: 'Olivia Martinez',
    department: 'Finance',
    baseSalary: 9166.67,
    allowances: 300,
    deductions: 260,
    netPay: 9206.67,
    paymentStatus: 'On Hold',
    payPeriod: 'June 2026',
  },
];

export const initialLoans: LoanRequest[] = [
  {
    id: 'LON001',
    employeeName: 'Marcus Vance',
    employeeRole: 'Enterprise Account Executive',
    amount: 5000,
    tenureMonths: 12,
    monthlyInstallment: 416.67,
    purpose: 'Emergency Home Repair',
    requestDate: '2026-06-15',
    status: 'Pending',
  },
  {
    id: 'LON002',
    employeeName: 'Elena Rostova',
    employeeRole: 'Growth Marketing Lead',
    amount: 3000,
    tenureMonths: 6,
    monthlyInstallment: 500.00,
    purpose: 'Education & Professional Development',
    requestDate: '2026-05-10',
    status: 'Approved',
  },
  {
    id: 'LON003',
    employeeName: 'David Kim',
    employeeRole: 'QA Engineer',
    amount: 1500,
    tenureMonths: 3,
    monthlyInstallment: 500.00,
    purpose: 'Medical bills clearance',
    requestDate: '2026-06-22',
    status: 'Pending',
  },
];

export const initialFeedback: FeedbackItem[] = [
  {
    id: 'FDB001',
    title: 'Flexible Friday Core Hours Proposal',
    category: 'Work Environment',
    sentiment: 'Positive',
    date: '2026-06-20',
    isAnonymous: true,
    content: 'Can we establish core focus hours on Fridays so that we have fewer meetings in the afternoon and can wrap up our sprints more effectively? Several team members are supportive of this.',
    status: 'Reviewed',
  },
  {
    id: 'FDB002',
    title: 'Dental Insurance Coverage Options',
    category: 'Benefits',
    sentiment: 'Neutral',
    date: '2026-06-21',
    isAnonymous: false,
    authorName: 'Sarah Connor',
    content: 'The current dental network is quite limited in our area. Could HR look into adding a secondary provider option during open enrollment?',
    status: 'New',
  },
  {
    id: 'FDB003',
    title: 'Unfair task allocation inside Product team',
    category: 'Management',
    sentiment: 'Negative',
    date: '2026-06-18',
    isAnonymous: true,
    content: 'There is excessive favoritism happening when big roadmap initiatives are allocated. It creates burnout for some and leaves others without growth opportunities.',
    status: 'Actioned',
  },
];

export const initialExits: ExitCase[] = [
  {
    id: 'EXT001',
    employeeName: 'David Kim',
    department: 'Engineering',
    role: 'QA Engineer',
    resignationDate: '2026-06-10',
    lastWorkingDay: '2026-07-10',
    reason: 'Accepted an offer with better growth scope at an early-stage startup.',
    status: 'Notice Period',
    interviewScheduled: true,
  },
  {
    id: 'EXT002',
    employeeName: 'Robert Vance',
    department: 'Sales',
    role: 'Sales Representative',
    resignationDate: '2026-05-15',
    lastWorkingDay: '2026-06-15',
    reason: 'Career path alignment and relocation to Colorado.',
    status: 'Completed',
    interviewScheduled: true,
  },
  {
    id: 'EXT003',
    employeeName: 'Sora Tanaka',
    department: 'Product',
    role: 'UX Researcher',
    resignationDate: '2026-06-22',
    lastWorkingDay: '2026-07-22',
    reason: 'Returning to graduate school for human-computer interaction.',
    status: 'Notice Period',
    interviewScheduled: false,
  },
];

export const initialSettings: SettingsConfig = {
  companyName: 'ALOK Operations Corp',
  contactEmail: 'hr-ops@alok-portal.com',
  currency: 'USD ($)',
  timezone: 'America/Los_Angeles',
  attendanceGraceMinutes: 15,
  enableNotifications: true,
  enableAnonymousFeedback: true,
};
